name: android-build
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make gradlew executable
      - run: chmod +x ./gradlew
      - name: Build with Gradle
      - run: ./gradlew assembleDebug